jwt:
  secret: QW5vdGhlckxvbmdTdXBlclNlY3JldEtleUZvckhTMjU2Qml0cw==

spring:
  application:
    name: video-streaming

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
      com.nevc: DEBUG

registration:
  default:
    role: ADMIN

video:
  publishPath: "uploads/"
